package com.web.dao;

import com.web.model.TRolePermission;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated
     */
    int insert(TRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated
     */
    TRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated
     */
    List<TRolePermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TRolePermission record);
}