package com.web.dao;

import com.web.model.TUserRole;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated
     */
    int insert(TUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated
     */
    List<TUserRole> selectAll();
}